### ISSUE TITLE
invalidation for non-safe methods

### ISSUE THREAD

**Issue by goofballLogic** [ForbesLindesay/http-basic#14]
RFC 7234 states:

> A cache MUST invalidate the effective Request URI (Section 5.5 of [RFC7230]) as well as the URI(s) in the Location and Content-Location response header fields (if present) when a non-error status code is received in response to an unsafe request method.
http://httpwg.org/specs/rfc7234.html#rfc.section.4.4

i.e. if you are doing a POST, PUT, DELETE etc to a resource, you should no longer hold on to a cache of the GET. 

The library doesn't adhere to this rule meaning that a POST followed by a GET can produce unexepcted results.

**Comment by goofballLogic** [comment]
Happy to contribute a pull request once you OK the approach. I need a working lib to do proper caching rather urgently.

**Comment by ForbesLindesay** [comment]
I had no idea about this part of the spec.  I'd be very happy to accept a pull request.

**Comment by goofballLogic** [comment]
Do you want tests for this withing the cache.js file, or in a distinct cache-invalidation.js ?

**Comment by goofballLogic** [comment]
Also, I note that the current API only returns one cached response object from Cache.getResponse.
As far as I can see, the spec allows for multiple representations to be stored against the same "primary key" (_read_ url) - for example one per "secondary key" (_read_ vary headers).

Is it ok to just ignore this part of the spec. and assume the library will only ever store one representation?

**Comment by ForbesLindesay** [comment]
I'm happy for this to just be added to existing files.  I think file-cache and memory-cache will both need an extra method of `invalidateResponse(url)`, which will also be a breaking change for anyone using a custom cache, as they will need to add this method themselves.

Yes, I think we should just stick to only having one cache per url.  It's a shortcut I took when writing the package that vastly simplifies things, improves performance in the most common case, and doesn't seem to have caused anyone serious issues.

**Comment by goofballLogic** [comment]
Just realised I need multiple caches per URL as part of my caching need is for vary by Authorization. Is that feasible for this library? (I'm willing to do the work).

**Comment by ForbesLindesay** [comment]
Yes, if you want to figure out a reasonably efficient implementation of this, I'm happy to merge support.

**Comment by goofballLogic** [comment]
is this pull request no good?

**Comment by ForbesLindesay** [comment]
Nothing wrong with it, just sometimes takes me a few days to get round to things.

**Comment by goofballLogic** [comment]
ah ok. thanks.
